data_path: "cluster2:s3://zhangtianyi1/Droid_episodes"
language_embedding_path: "cluster2:s3://zhangtianyi1/Droid_language_embeddings"
extrinsic_path: "/mnt/petrelfs/share_data/caoliu/Droid_extrinsics"
traj_per_episode: 8
traj_length: 15
cameras_per_scene: 6
use_baseframe_action: False
split_type: null
train_data_list: null
eval_data_list: null
stride: 5
gripper_type: 'next_observation' # 'current_action' or 'next_observation'

action_spec:
  world_vector: 
    tensor: 3
    minimum: -0.1024
    maximum: 0.1024
  rotation_delta:
    tensor: 4
    minimum: -0.1024
    maximum: 0.1024
  gripper_closedness_action:
    tensor: 1
    minimum: 0.0
    maximum: 1.0
  terminate_episode:
    tensor: 3
    minimum: 0
    maximum: 1