data_path: 'cluster3:s3://zhangtianyi1/Sim_Data/ManiSkill2-camerabase1/'
language_embedding_path: 'cluster3:s3://zhangtianyi1/Sim_Data_language_embeddings_77token_camerabase1/'
traj_per_episode: 2
traj_length: 2
include_target: 1
num_given_observation: 2
cameras_per_scene: 20
use_baseframe_action: false
aug_gripper_status_pose: 0
split_type: 'fix_traj'
use_euler: 0
train_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/maniskill_fewcam_datalist/balanced_train_list.pkl'
eval_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/maniskill_fewcam_datalist/balanced_eval_list.pkl'
stride: 4
# close_loop_eval_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/FilePath/close_loop_eval_data_list_200.pkl'
# close_loop_eval_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/FilePath/hold_25_class_ycb_close_loop_eval_data_list.pkl'
close_loop_eval_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/maniskill_fewcam_datalist/balanced_close_loop_eval_list.pkl'