data_path: 'cluster3:s3://zhangtianyi1/Sim_Data/ManiSkill2-0503/'
language_embedding_path: 'cluster3:s3://zhangtianyi1/Sim_Data_language_embeddings_77token_0503'
traj_per_episode: 2
traj_length: 2
cameras_per_scene: 20
use_baseframe_action: false
split_type: 'fix_traj'
num_given_observation: 2
train_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/maniskill2_0503_datalist/full_in_domain_balanced_train_list.pkl'
eval_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/maniskill2_0503_datalist/full_in_domain_balanced_eval_list.pkl'
stride: 4
# close_loop_eval_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/FilePath/close_loop_eval_data_list_200.pkl'
# close_loop_eval_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/FilePath/hold_25_class_ycb_close_loop_eval_data_list.pkl'
close_loop_eval_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/maniskill2_0503_datalist/full_in_domain_close_loop_eval_list.pkl'
