data_path: 'cluster2:s3://zhangtianyi1/Sim_Data'
language_embedding_path: 'cluster2:s3://zhangtianyi1/Sim_Data_language_embeddings_77token'
traj_per_episode: 8
traj_length: 15
cameras_per_scene: 6
use_baseframe_action: false
split_type: 'overfit'
train_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/FilePath/overfit_data_cam_list.pkl'
eval_data_list: '/mnt/petrelfs/share_data/zhangtianyi1/Dataset/Sim_Data/FilePath/overfit_data_cam_list.pkl'
stride: 4
